name 'blacksquarelabs-openssh'
maintainer 'John Coleman'
maintainer_email 'chef@blacksquarelabs.com'
license 'Apache 2.0'
description 'Installs/Configures blacksquarelabs-openssh'
long_description 'Installs/Configures blacksquarelabs-openssh'
version '0.1.3'
depends 'openssh', '= 1.6.1'
